%% generated by soap from: /home/james/Development/pegasus/PegPay.wsdl
%% for service "PegPay" and port "PegPaySoap"
%% using options: [{service,"PegPay"},{port,"PegPaySoap"},{generate,client},{namespaces,[{"http://PegPayPaymentsApi/",undefined}]},{generate_tests,client},{http_client,soap_client_ibrowse},{client_name,"PegPay_client"},{strict,true}]

-module('PegPay_client').

-include("PegPay.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export(['GetServerStatus'/3]).
-export(['GetTransactionDetails'/3]).
-export(['QuerySchoolDetails'/3]).
-export(['QueryCustomerDetails'/3]).
-export(['PostTransaction'/3]).
-export(['GetPayTVBouquetDetails'/3]).
-export(['ReactivatePayTvCard'/3]).
-export(['UploadEndOfDayReport'/3]).
-export(['PrepaidVendorPostTransaction'/3]).
-export(['ReversePrepaidTransaction'/3]).

-spec 'GetServerStatus'(Soap_body::'GetServerStatus'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('GetServerStatusResponse'()).
'GetServerStatus'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://PegPayPaymentsApi/GetServerStatus\"", interface()).

-spec 'GetTransactionDetails'(Soap_body::'GetTransactionDetails'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('GetTransactionDetailsResponse'()).
'GetTransactionDetails'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://PegPayPaymentsApi/GetTransactionDetails\"", interface()).

-spec 'QuerySchoolDetails'(Soap_body::'QuerySchoolDetails'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('QuerySchoolDetailsResponse'()).
'QuerySchoolDetails'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://PegPayPaymentsApi/QuerySchoolDetails\"", interface()).

-spec 'QueryCustomerDetails'(Soap_body::'QueryCustomerDetails'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('QueryCustomerDetailsResponse'()).
'QueryCustomerDetails'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://PegPayPaymentsApi/QueryCustomerDetails\"", interface()).

-spec 'PostTransaction'(Soap_body::'PostTransaction'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('PostTransactionResponse'()).
'PostTransaction'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://PegPayPaymentsApi/PostTransaction\"", interface()).

-spec 'GetPayTVBouquetDetails'(Soap_body::'GetPayTVBouquetDetails'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('GetPayTVBouquetDetailsResponse'()).
'GetPayTVBouquetDetails'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://PegPayPaymentsApi/GetPayTVBouquetDetails\"", interface()).

-spec 'ReactivatePayTvCard'(Soap_body::'ReactivatePayTvCard'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('ReactivatePayTvCardResponse'()).
'ReactivatePayTvCard'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://PegPayPaymentsApi/ReactivatePayTvCard\"", interface()).

-spec 'UploadEndOfDayReport'(Soap_body::'UploadEndOfDayReport'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('UploadEndOfDayReportResponse'()).
'UploadEndOfDayReport'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://PegPayPaymentsApi/UploadEndOfDayReport\"", interface()).

-spec 'PrepaidVendorPostTransaction'(Soap_body::'PrepaidVendorPostTransaction'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('PrepaidVendorPostTransactionResponse'()).
'PrepaidVendorPostTransaction'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://PegPayPaymentsApi/PrepaidVendorPostTransaction\"", interface()).

-spec 'ReversePrepaidTransaction'(Soap_body::'ReversePrepaidTransaction'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('ReversePrepaidTransactionResponse'()).
'ReversePrepaidTransaction'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://PegPayPaymentsApi/ReversePrepaidTransaction\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.