%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-type anyAttrib()  :: {{string(),    %% name of the attribute
                        string()},   %% namespace
                       string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.

%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
                localPart :: string(),
                prefix :: string(),
                mappedPrefix :: string()}).



-record('AutoCreate', {anyAttribs :: anyAttribs(),
	'Response' :: 'AutoCreate/Response'()}).

-type 'AutoCreate'() :: #'AutoCreate'{}.


-record('AutoCreate/Response', {anyAttribs :: anyAttribs(),
	'Status' :: string(),
	'StatusCode' :: string(),
	'StatusMessage' :: string(),
	'ErrorMessageCode' :: string(),
	'ErrorMessage' :: string(),
	'TransactionStatus' :: string(),
	'TransactionReference' :: string()}).

-type 'AutoCreate/Response'() :: #'AutoCreate/Response'{}.