-record(pegasus_settings,{
  api_username,
  api_password,
  payment_url,
  notification_url,
  failure_url,
  private_key_password
}).

-record(signature_keys, {
  private_key,
  id,
  public_key
}).

%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-type anyAttrib()  :: {{string(),    %% name of the attribute
  string()},   %% namespace
  string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.

%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
  localPart :: string(),
  prefix :: string(),
  mappedPrefix :: string()}).



-record('AutoCreate', {anyAttribs :: anyAttribs(),
  'Request' :: 'AutoCreate/Request'()}).

-type 'AutoCreate'() :: #'AutoCreate'{}.


-record('AutoCreate/Request', {anyAttribs :: anyAttribs(),
  'APIUsername' :: string(),
  'APIPassword' :: string(),
  'Method' :: string(),
  'NonBlocking' :: string(),
  'Amount' :: string(),
  'Account' :: string(),
  'AccountProviderCode' :: string(),
  'Narrative' :: string(),
  'NarrativeFileName' :: string()  | undefined,
  'NarrativeFileBase64' :: string()  | undefined,
  'InternalReference' :: string()  | undefined,
  'ExternalReference' :: string(),
  'ProviderReferenceText' :: string(),
  'InstantNotificationUrl' :: string(),
  'FailureNotificationUrl' :: string(),
  'AuthenticationSignatureBase64' :: string()}).

-type 'AutoCreate/Request'() :: #'AutoCreate/Request'{}.

-record(check_transaction_status, {
  'APIUsername' :: string(),
  'APIPassword' :: string(),
  'Method' :: string(),
  'PrivateTransactionReference' :: string(),
  'DepositTransactionType' :: string()
}).
